{"name": "test_SearchUser_Excel_DDT_006", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'iter_parents'", "trace": "self = <allure_pytest.listener.AllureListener object at 0x0000026B270A0710>, item = <Function test_SearchUser_Excel_DDT_006>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_runtest_setup(self, item):\n        if not self._cache.get(item.nodeid):\n            uuid = self._cache.push(item.nodeid)\n            test_result = TestResult(name=item.name, uuid=uuid, start=now(), stop=now())\n            self.allure_logger.schedule_test(uuid, test_result)\n        yield\n>       self._update_fixtures_children(item)\n\n..\\..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\allure_pytest\\listener.py:102: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\allure_pytest\\listener.py:71: in _update_fixtures_children\n    for fixturedef in _test_fixtures(item):\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nitem = <Function test_SearchUser_Excel_DDT_006>\n\n    def _test_fixtures(item):\n        fixturemanager = item.session._fixturemanager\n        fixturedefs = []\n    \n        if hasattr(item, \"_request\") and hasattr(item._request, \"fixturenames\"):\n            for name in item._request.fixturenames:\n>               fixturedefs_pytest = fixturemanager.getfixturedefs(name, item.nodeid)\nE               AttributeError: 'str' object has no attribute 'iter_parents'\n\n..\\..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\allure_pytest\\listener.py:345: AttributeError"}, "start": 1742989255083, "stop": 1742989255083, "uuid": "6dbc9ebd-c9bc-44e3-b231-286e9ac28ce7", "historyId": "6adf97f83acf6453d4a6a4b1070f3754", "labels": [{"name": "tag", "value": "@pytest.mark.skip(reason='Too much confusion while providing wrong data in excel test case failed, test case can't handle it')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_SearchUser_Excel_DDT"}, {"name": "subSuite", "value": "Test_SearchUser_Class"}, {"name": "host", "value": "LAPTOP-L938VQFB"}, {"name": "thread", "value": "19232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_SearchUser_Excel_DDT"}]}